openapi: 3.0.3
info:
  title: Front
  description: Front
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
tags:
  - name: client
    description: Front request handler
paths:
  "/simple/client/{id}":
    get:
      tags:
        - client
      summary: get clint by id
      operationId: getById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: ZBS
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientGetResultDto"


components:
  schemas:
    ClientGetResultDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        surname:
          type: string
        email:
          type: string
        phoneNumber:
          type: string


