openapi: 3.0.3
info:
  title: Store
  description: Store shows Product(s)
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
tags:
  - name: store
    description: shop handler
paths:
  "/store/product":
    get:
      tags:
        - product
      summary: get all products by id from warehouse
      operationId: getAll
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductResultDto"


components:
  schemas:
    ProductResultDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: integer
          format: int32
        amount:
          type: integer
          format: int32